AVWebsite/Models/Tour/TourPackage.cs
using System;
namespace AVWebsite.Models.Tour
{
    public class TourPackage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Inclusion { get; set; }
        public string Exclusion { get; set; }
        public string Image { get; set; }
        public float UnitPrice { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int MaximumPersion { get; set; }
        public int MinimumPerson { get; set; }
        public int Qty { get; set; }
        public string UnitName { get; set; }
    }
}

AVWebsite/Controllers/TourPackageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AVWebsite.Models;
using AVWebsite.Models.Tour;
using AVWebsite.Models.ViewModels.Tour;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AVWebsite.Controllers
{
    public class TourPackageController : Controller
    {
        private readonly AppDbContext db;
        private readonly IHostingEnvironment hostingEnvironment;
        public TourPackageController(AppDbContext db, IHostingEnvironment hostingEnvironment)
        {
            this.db = db;
            this.hostingEnvironment = hostingEnvironment;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var result = (from c in db.TourPackages
                          select new TourPackage
                          {
                              Id = c.Id,
                              Title = c.Title,
                              Description = c.Description,
                              Image = c.Image,
                          }).ToList();

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TourPackageVM obj)
        {
            
                var startDate = DateTime.Parse(obj.StartDate);
                var endDate = DateTime.Parse(obj.EndDate);
                string uniqueFileName = null;
                if (obj.Image != null)
                {
                    string upload = Path.Combine(hostingEnvironment.WebRootPath, "images/tourPackageImages");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + obj.Image.FileName;
                    string filePath = Path.Combine(upload, uniqueFileName);
                    obj.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                TourPackage tourPackage = new TourPackage
                {
                    Title = obj.Title,
                    Description = obj.Description,
                    Inclusion = obj.Inclusion,
                    Exclusion = obj.Exclusion,
                    Image = uniqueFileName,
                    UnitName = obj.UnitName,
                    UnitPrice = obj.UnitPrice,
                    StartDate = startDate,
                    EndDate = endDate,
                    MaximumPersion = obj.MaximumPersion,
                    MinimumPerson = obj.MinimumPerson,
                    Qty = obj.Qty,

                };
                db.TourPackages.Add(tourPackage);
                db.SaveChanges();
                return RedirectToAction("details", new { id = tourPackage.Id });
          
        }




        // POST-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = db.TourPackages.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            db.TourPackages.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {


            var obj = db.TourPackages.Find(id);
            var tourPackage = new TourPackage
            {
                Title = obj.Title,
                Description = obj.Description,
                Inclusion = obj.Inclusion,
                Exclusion = obj.Exclusion,
                Image = obj.Image,
                UnitName = obj.UnitName,
                UnitPrice = obj.UnitPrice,
                StartDate = obj.StartDate,
                EndDate = obj.EndDate,
                MaximumPersion = obj.MaximumPersion,
                MinimumPerson = obj.MinimumPerson,
                Qty = obj.Qty,

            };
            return View(tourPackage);
        }

        [HttpPost]
        public IActionResult Edit(TourPackage obj)
        {
            if (ModelState.IsValid)
            {
                var model = db.TourPackages.FirstOrDefault(x => x.Id == obj.Id);
                model.Title = obj.Title;
                model.Description = obj.Description;
                model.Inclusion = obj.Inclusion;
                model.Exclusion = obj.Exclusion;
                model.Image = obj.Image;
                model.UnitName = obj.UnitName;
                model.UnitPrice = obj.UnitPrice;
                model.StartDate = obj.StartDate;
                model.EndDate = obj.EndDate;
                model.MaximumPersion = obj.MaximumPersion;
                model.MinimumPerson = obj.MinimumPerson;
                model.Qty = obj.Qty;


                db.TourPackages.Update(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var location = db.Locations.Find(id);
            Location locationVM = new Location
            {
                Id = location.Id,
                Description = location.Description,
                Name = location.Name,
                FeatureImage = location.FeatureImage,
            };
            return View(locationVM);
        }
    }
}

AVWebsite/Views/TourPackage/Create.cshtml
@model AVWebsite.Models.ViewModels.Tour.TourPackageVM

@{
    ViewData["Title"] = "Create New TourPackage";
}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        $("#startDate, #endDate").kendoDateTimePicker({
            value: new Date(),
            format: "dd MMM yy",
            dateInput: false
        });
    });
</script>
<h1>Create New Tour Package</h1>

<br />
<br />
<div class="card card-flush pt-3 mb-5 mb-xl-10">
    <br />
    <div class="container">
        <form enctype="multipart/form-data" asp-action="Create" asp-controller="TourPackage" method="post">
            <input asp-for="Id" type="text" hidden />
            <div class="row">
                <div class="form-group col-6">
                    <label>Tour Package Name</label>
                    <input asp-for="Title" type="text" class="form-control" id="name" />
                </div>
                <div class="form-group col-3">
                    <label>Select Unit Name Tag</label>
                    <select id="unitName" asp-for="UnitName" class="form-select form-select-solid form-select-lg fw-bold">
                        <option value="">Select Package Unit</option>
                        <option value="Per Person">Per Person</option>
                        <option value="Per Package">Per Package</option>
                        <option value="Per Car">Per Car</option>
                        <option value="Per Boat">Per Boat</option>
                    </select>
                </div>
                <div class="form-group col-3">
                    <label>Unit Price</label>
                    <input asp-for="UnitPrice" type="number" class="form-control" />
                </div>
            </div>
            <div class="form-group col-10">
                <label>Package Description</label>
                <textarea id="description" asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    <label>Package Inclusion</label>
                    <textarea asp-for="Inclusion" class="form-control"></textarea>
                </div>
                <div class="form-group col-6">
                    <label>Package Exclusion</label>
                    <textarea asp-for="Exclusion" class="form-control"></textarea>
                </div>

            </div>
           <br />
            <div class="row">
                <div class="form-group col-3">
                    <label>Package Start Date</label>
                    <input id="startDate" asp-for="StartDate" class="form-control" />

                </div>
                <div class="form-group col-3">
                    <label>Package End Date</label>
                    <input id="endDate" asp-for="EndDate" class="form-control" />
                </div>
                <div class="form-group col-3">
                    <label>Maximum Persion</label>
                    <input asp-for="MaximumPersion" type="number" class="form-control" />
                </div>
                <div class="form-group col-3">
                    <label>Minimium Persion</label>
                    <input asp-for="MinimumPerson" type="number" class="form-control" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="form-group col-3">
                    <label>Quantity</label>
                    <input asp-for="Qty" type="number" class="form-control" />
                </div>
                <div class="form-group col-6">
                    <label>Feature Image</label>
                    <div class="custom-file">
                        <input asp-for="Image" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {


    <script>$(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });</script>
    <script>$(document).ready(function () {
            $('#description').richText();
        });</script>


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}