AVWebsite/Models/Location.cs
using System;
using Microsoft.AspNetCore.Http;

namespace AVWebsite.Models
{
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FeatureImage { get; set; }
    }
    
}

AVWebsite/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AVWebsite.Models;
using AVWebsite.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace AVWebsite.Controllers
{
    public class LocationController : Controller
    {
        private readonly AppDbContext db;
        private readonly IHostingEnvironment hostingEnvironment;
        public LocationController(AppDbContext db, IHostingEnvironment hostingEnvironment)
        {
            this.db = db;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            var result = (from c in db.Locations
                          select new Location
                          {
                              Id = c.Id,
                              Name = c.Name,
                              Description = c.Description,
                              FeatureImage = c.FeatureImage,
                          }).ToList(); 

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LocationVM obj)
        {
            if (ModelState.IsValid) 
            {
                string uniqueFileName = null;
                if(obj.FeatureImage != null)
                {
                    string upload = Path.Combine(hostingEnvironment.WebRootPath, "images/locationImages");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + obj.FeatureImage.FileName;
                    string filePath = Path.Combine(upload, uniqueFileName);
                    obj.FeatureImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                Location location = new Location
                {
                    Name = obj.Name,
                    Description = obj.Description,
                    FeatureImage = uniqueFileName
                };
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("details", new {id = location.Id });
            }
            return View();
        }




        // POST-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = db.Locations.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            db.Locations.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {


            var model = db.Locations.Find(id);
            var location = new Location
            {
                Name = model.Name,

            };
            return View(location);
        }

        [HttpPost]
        public IActionResult Edit(Location model)
        {
            if (ModelState.IsValid)
            {
                var pr = db.Locations.FirstOrDefault(x => x.Id == model.Id);
                pr.Name = model.Name;


                db.Locations.Update(pr);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var location = db.Locations.Find(id);
            Location locationVM = new Location
            {
                Id = location.Id,
                Description = location.Description,
                Name = location.Name,
                FeatureImage = location.FeatureImage,
            };
            return View(locationVM);
        }
    }
}

AVWebsite/Views/Location/Create.cshtml
@model AVWebsite.Models.ViewModels.LocationVM

@{
    ViewData["Title"] = "Create Location";
}

<h2>Create New Location"</h2>

<br />
<div class="dan"></div>
<div class="card card-flush pt-3 mb-5 mb-xl-10">
    <div class="container">


        <form enctype="multipart/form-data" asp-controller="Location" method="post" asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
                <div class="col-6 form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-10 form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            <br />
           
            <div class="form-group row">

                <label class="col-sm-2 col-form-label">Feature Image</label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="FeatureImage" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>


    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {

   
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
        <script>$(document).ready(function () {
                $('textarea').richText();
            });</script>
    
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AVWebsite/Views/Location/Details.cshtml
@model AVWebsite.Models.Location

@{
    ViewData["Title"] = "Location Detail";
    var imagePath = "~/images/locationImages/" + Model.FeatureImage;
}

<div class="card card-flush pt-3 mb-5 mb-xl-10">

    <!--begin::Alert-->
    <div class="alert alert-primary">
        <span class="menu-icon me-0">

        </span>
        <div class="d-flex flex-column">
            <!--begin::Title-->
            <h1 class="mb-1 text-center text-dark">@Model.Name</h1>

        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Alert-->
    <div class="card-body pt-3">
        <div class="mb-10">

            

            <table class="table fs-6 fw-bold gs-0 gy-2 gx-2 m-0">

                <tr>
                    <td class="text-gray-400">Location Description:</td>

                </tr>
                <tr>
                    <td>@Html.Raw(@Model.Description)</td>
                </tr>

            </table>
            <br />
            <br />
            <div class="container">
                <img src="@imagePath" class="img-fluid" alt="..." asp-append-version="true">
            </div>
        </div>

    </div>

</div>

AVWebsite/Views/Location/Index.cshtml
@model IEnumerable<Location>

@{
    ViewBag.Title = "Location List";
}


<div class="card-deck">
    @foreach (var location in Model)
    {
        var imagePath = "~/images/locationImages/" + location.FeatureImage;

        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <br />
            <div class="card-header">
                <h3>@location.Name</h3>
            </div>

            <img class="card-img-top imageThumbnail" src="@imagePath"
                 asp-append-version="true" />

            <div class="card-footer text-center">
                <a asp-controller="home" asp-action="details" asp-route-id="@location.Id"
                   class="btn btn-primary m-1">View</a>
                <a href="#" class="btn btn-primary m-1">Edit</a>
                <a href="#" class="btn btn-danger m-1">Delete</a>
            </div>
        </div>
    }
</div>