AVWebsite/Models/AdditionalService.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AVWebsite.Models
{
    public class AdditionalService
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FeatureImage { get; set; }
        public float Price { get; set; }
        public DateTime EndDate { get; set; }
    }
}

AVWebsite/Controllers/AdditionalServiceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AVWebsite.Models;
using AVWebsite.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AVWebsite.Controllers
{
    public class AdditionalServiceController : Controller
    {
        private readonly AppDbContext db;
        private readonly IHostingEnvironment hostingEnvironment;
        public AdditionalServiceController(AppDbContext db, IHostingEnvironment hostingEnvironment)
        {
            this.db = db;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            var result = (from c in db.AdditionalServices
                          select new AdditionalService
                          {
                              Id = c.Id,
                              Name = c.Name,
                              Description = c.Description,
                              FeatureImage = c.FeatureImage,
                              Price = c.Price,
                              EndDate = c.EndDate

                          }).ToList();

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AdditionalServiceVM obj)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (obj.FeatureImage != null)
                {
                    string upload = Path.Combine(hostingEnvironment.WebRootPath, "images/additionalServices");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + obj.FeatureImage.FileName;
                    string filePath = Path.Combine(upload, uniqueFileName);
                    obj.FeatureImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                var date = Convert.ToDateTime(obj.EndDate);
                AdditionalService aService = new AdditionalService
                {
                    Name = obj.Name,
                    Description = obj.Description,
                    FeatureImage = uniqueFileName,
                    Price = obj.Price,
                    EndDate = date,
                };
                db.AdditionalServices.Add(aService);
                db.SaveChanges();
                return RedirectToAction("details", new { id = aService.Id });
            }
            return View();
        }




        // POST-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = db.AdditionalServices.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            db.AdditionalServices.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {


            var model = db.AdditionalServices.Find(id);
            var service = new AdditionalService
            {
                Name = model.Name,
                Description = model.Description,
                Price = model.Price,
                FeatureImage = model.FeatureImage,
                EndDate = model.EndDate,

            };
            return View(service);
        }

        [HttpPost]
        public IActionResult Edit(AdditionalService model)
        {
            if (ModelState.IsValid)
            {
                var pr = db.AdditionalServices.FirstOrDefault(x => x.Id == model.Id);
                pr.Name = model.Name;
                pr.Description = model.Description;
                pr.FeatureImage = model.FeatureImage;
                pr.Price = model.Price;
                pr.EndDate = model.EndDate;

                db.AdditionalServices.Update(pr);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var location = db.AdditionalServices.Find(id);
            AdditionalService locationVM = new AdditionalService
            {
                Id = location.Id,
                Description = location.Description,
                Name = location.Name,
                Price = location.Price,
                EndDate = location.EndDate,
                FeatureImage = location.FeatureImage,
            };
            return View(locationVM);
        }
    }
}

AVWebsite/Views/AdditionalService/Create.cshtml
@model AVWebsite.Models.ViewModels.AdditionalServiceVM

@{
    ViewData["Title"] = "Create Additinal Service";
}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        $("#endDate").kendoDateTimePicker({
            value: new Date(),
            format: "dd MMM yy",
            dateInput: false
        });
    });
</script>

<h2>Create New Additional Service"</h2>

<br />
<div class="dan"></div>
<div class="card card-flush pt-3 mb-5 mb-xl-10">
    <div class="container">


        <form enctype="multipart/form-data" asp-controller="AdditionalService" method="post" asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-4 form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-4 form-group">
                    <label asp-for="EndDate" class="control-label">End Date</label>
                    <input asp-for="EndDate" class="form-control" id="endDate" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
                <div class="col-4 form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input type="number" asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="col-10 form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group row">

                <label class="col-sm-2 col-form-label">Feature Image</label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="FeatureImage" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>


    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {


    <script>$(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });</script>
    <script>$(document).ready(function () {
            $('textarea').richText();
        });</script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AVWebsite/Views/AdditionalService/Details.cshtml
@model AVWebsite.Models.AdditionalService

@{
    ViewData["Title"] = "Additional Service Detail";
    var imagePath = "~/images/additionalServices/" + Model.FeatureImage;
}

<div class="card card-flush pt-3 mb-5 mb-xl-10">

    <!--begin::Alert-->
    <div class="alert alert-primary">
        <span class="menu-icon me-0">

        </span>
        <div class="d-flex flex-column">
            <!--begin::Title-->
            <h1 class="mb-1 text-center text-dark">@Model.Name</h1>

        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Alert-->
    <div class="card-body pt-3">
        <div class="mb-10">

            

            <table class="table fs-6 fw-bold gs-0 gy-2 gx-2 m-0">

                <tr>
                    <td class="text-gray-400">Price:</td>
                    <td class="text-gray-400">End Date:</td>
                    <td class="text-gray-400">Description:</td>

                </tr>
                <tr>
                    <td>@Model.Price</td>
                    <td>@Model.EndDate</td>
                    <td>@Html.Raw(@Model.Description)</td>
                </tr>

            </table>
            <br />
            <br />
            <div class="container">
                <img src="@imagePath" class="img-fluid" alt="..." asp-append-version="true">
            </div>
        </div>

    </div>

</div>

AVWebsite/Views/AdditionalService/Index.cshtml
@model IEnumerable<AdditionalService>

@{
    ViewBag.Title = "Additioanl Services List";
}

<p>
    <a class="btn btn-dark " asp-controller="AdditionalService" asp-action="Create">Create New Additional Service</a>
</p>

<div class="card-deck">
    @foreach (var location in Model)
    {
        var imagePath = "~/images/additionalServices/" + location.FeatureImage;

        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <br />
            <div class="card-header">
                <h3>@location.Name</h3>
            </div>

            <img class="card-img-top imageThumbnail" src="@imagePath"
                 asp-append-version="true" />

            <div class="card-footer text-center">
                <a asp-controller="AdditionalService" asp-action="details" asp-route-id="@location.Id"
                   class="btn btn-primary m-1">View</a>
                <a href="#" class="btn btn-primary m-1">Edit</a>
                <a href="#" class="btn btn-danger m-1">Delete</a>
            </div>
        </div>
    }
</div>